# This is a basic workflow to help you get started with Actions

name: backend-deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # these are for storing database access information into github secret
  # for github actions to directly access them.
  DB_USER: '${{ secrets.DB_USER }}'
  DB_PASS: '${{ secrets.DB_PASS }}'
  DB_NAME: '${{ secrets.DB_NAME }}'
  DB_TEST_NAME: '${{ secrets.DB_TEST_NAME }}'
  INSTANCE_CONNECTION_NAME: '${{ secrets.INSTANCE_CONNECTION_NAME }}'
  
jobs:
  deploy:
    defaults:
        run:
          working-directory: ./backend
    environment: backend
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - uses: JinghuaWang/gcp-yaml-compiler@v1.0
      with:
        file: ./backend/app.yaml
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      # this line will automatically build maven, and while building maven, maven test will run all the tests.
      run: mvn package --file pom.xml
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: ./backend/app.yaml
        version: v1
        project_id: aroundu-403

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
